type Composer = {
  id: number;
  lastName: string;
  firstName: string; // nullable
  firstAbbreviation: string; // nullable
}[];

export const composers: Composer = [
  {
    id: 1,
    lastName: 'Bach',
    firstName: 'Johann Sebastian',
    firstAbbreviation: 'J. S.',
  },
  {
    id: 2,
    lastName: 'Handel',
    firstName: 'George Frideric',
    firstAbbreviation: 'G. F.',
  },
  {
    id: 3,
    lastName: 'Lully',
    firstName: 'Jean-Baptiste',
    firstAbbreviation: 'J.-B.',
  },
  {
    id: 4,
    lastName: 'Finger',
    firstName: 'Godfrey',
    firstAbbreviation: 'G.',
  },
  {
    id: 5,
    lastName: 'Paisible',
    firstName: 'James',
    firstAbbreviation: 'J.',
  },
  {
    id: 6,
    lastName: 'Corrette',
    firstName: 'Michel',
    firstAbbreviation: 'M.',
  },
  {
    id: 7,
    lastName: 'De Fesch',
    firstName: 'Willem',
    firstAbbreviation: 'W.',
  },
  {
    id: 8,
    lastName: 'Fedeli "Saggione"',
    firstName: 'Giuseppe',
    firstAbbreviation: 'G.',
  },
  {
    id: 9,
    lastName: 'Mell',
    firstName: 'Davis',
    firstAbbreviation: 'D.',
  },
  {
    id: 10,
    lastName: 'Beckett',
    firstName: 'Philip',
    firstAbbreviation: 'P.',
  },
  {
    id: 11,
    lastName: 'de Boismortier',
    firstName: 'Joseph Bodin',
    firstAbbreviation: 'J. B.',
  },
  {
    id: 12,
    lastName: 'Philidor "L\'Aîné"',
    firstName: 'André Danican',
    firstAbbreviation: 'A. D.',
  },
  {
    id: 13,
    lastName: 'Banister',
    firstName: 'John',
    firstAbbreviation: 'J.',
  },
  {
    id: 14,
    lastName: 'King',
    firstName: 'Robert',
    firstAbbreviation: 'R.',
  },
  {
    id: 15,
    lastName: 'Dowland',
    firstName: 'John',
    firstAbbreviation: 'J.',
  },
  {
    id: 16,
    lastName: 'Ford',
    firstName: 'Thomas',
    firstAbbreviation: 'T.',
  },
  {
    id: 17,
    lastName: 'Schein',
    firstName: 'Johann Hermann',
    firstAbbreviation: 'J. H.',
  },
  {
    id: 18,
    lastName: 'Susato',
    firstName: 'Tielman',
    firstAbbreviation: 'T.',
  },
  {
    id: 19,
    lastName: 'Widmann',
    firstName: 'Erasmus',
    firstAbbreviation: 'E.',
  },
  {
    id: 20,
    lastName: 'Phalèse',
    firstName: 'Pierre',
    firstAbbreviation: 'P.',
  },
  {
    id: 21,
    lastName: 'Fischer',
    firstName: 'Johann Caspar Ferdinand',
    firstAbbreviation: 'J. C. F.',
  },
  {
    id: 22,
    lastName: 'Delavigne',
    firstName: 'Philibert',
    firstAbbreviation: 'P.',
  },
  {
    id: 23,
    lastName: 'Chédeville',
    firstName: 'Esprit-Philippe',
    firstAbbreviation: 'E.-P.',
  },
  {
    id: 24,
    lastName: 'Naudot',
    firstName: 'Jacques-Christophe',
    firstAbbreviation: 'E.-P.',
  },
  {
    id: 25,
    lastName: 'Couperin',
    firstName: 'François',
    firstAbbreviation: 'F',
  },
  {
    id: 26,
    lastName: 'Hassler',
    firstName: 'Hans Leo',
    firstAbbreviation: 'H. L.',
  },
  {
    id: 27,
    lastName: 'Arbeau',
    firstName: 'Thoinot',
    firstAbbreviation: 'T.',
  },
  {
    id: 28,
    lastName: 'del Encina',
    firstName: 'Juan',
    firstAbbreviation: 'J.',
  },
  {
    id: 29,
    lastName: 'Gastoldi',
    firstName: 'Giovanni Giacomo',
    firstAbbreviation: 'G. G.',
  },
  {
    id: 30,
    lastName: 'Anon.',
    firstName: '',
    firstAbbreviation: '',
  },
  {
    id: 31,
    lastName: "de Caix d'Hervelois",
    firstName: 'Louis',
    firstAbbreviation: 'L.',
  },
  {
    id: 32,
    lastName: 'Delalande',
    firstName: 'Michel-Richard',
    firstAbbreviation: 'L.',
  },
  {
    id: 33,
    lastName: 'Franck',
    firstName: 'Melchior',
    firstAbbreviation: 'M.',
  },
  {
    id: 34,
    lastName: 'Attaingnant',
    firstName: 'Pierre',
    firstAbbreviation: 'P.',
  },
  {
    id: 35,
    lastName: 'Gervaise',
    firstName: 'Claude',
    firstAbbreviation: 'C.',
  },
  {
    id: 36,
    lastName: 'de Sermisy',
    firstName: 'Claudin',
    firstAbbreviation: 'C.',
  },
  {
    id: 37,
    lastName: 'Campion',
    firstName: 'Thomas',
    firstAbbreviation: 'T.',
  },
  {
    id: 38,
    lastName: 'Kapsberger',
    firstName: 'Giovanni Girolamo',
    firstAbbreviation: 'G. G.',
  },
  {
    id: 39,
    lastName: 'Keene',
    firstName: 'Edward',
    firstAbbreviation: 'E.',
  },
  {
    id: 40,
    lastName: 'Hart',
    firstName: 'James',
    firstAbbreviation: 'J.',
  },
  {
    id: 41,
    lastName: 'Bertin de la Doué',
    firstName: 'Thomas',
    firstAbbreviation: 'T.',
  },
  {
    id: 42,
    lastName: 'Marquis de Dampierre',
    firstName: 'Marc Antoine',
    firstAbbreviation: 'M. A.',
  },
  {
    id: 43,
    lastName: 'Bâton',
    firstName: 'Charles',
    firstAbbreviation: 'C.',
  },
];
