type Edition = {
  id: number;
  article_no: string;
  title: string;
  supplementary_title: string;
  price: number;
  material_id: number;
  category_id: number;
  instrument_no: number;
}[];

export const editions: Edition = [
  {
    id: 1,
    article_no: 'OM501',
    title: 'Gambenschule für Kinder, 1. Teil (German only)',
    supplementary_title: '(German only)',
    price: 16,
    material_id: 1,
    category_id: 1,
    instrument_no: 1,
  },
  {
    id: 2,
    article_no: 'OM502',
    title: 'Gambenschule für Kinder, 1. Teil (German only)',
    supplementary_title: '(German only)',
    price: 16,
    material_id: 2,
    category_id: 2,
    instrument_no: 1,
  },
  {
    id: 3,
    article_no: 'OM521',
    title: 'Gambenschule für Kinder, 2. Teil (German only)',
    supplementary_title: '(German only)',
    price: 11,
    material_id: 3,
    category_id: 3,
    instrument_no: 1,
  },
  {
    id: 4,
    article_no: 'OM520',
    title: 'Gambenschule für Kinder, 2. Teil (German only)',
    supplementary_title: '(German only)',
    price: 11,
    material_id: 4,
    category_id: 4,
    instrument_no: 1,
  },
  {
    id: 5,
    article_no: 'OM519a',
    title: 'Weihnachtslieder für Diskant- & Altgambe',
    supplementary_title: '(German only)',
    price: 10,
    material_id: 5,
    category_id: 5,
    instrument_no: 2,
  },
  {
    id: 6,
    article_no: 'OM519b',
    title: 'Weihnachtslieder für Alt- & Bassgambe',
    supplementary_title: '(German only)',
    price: 10,
    material_id: 6,
    category_id: 6,
    instrument_no: 2,
  },
  {
    id: 7,
    article_no: 'OM503',
    title:
      'Easy Baroque Pieces for Treble Viol with accompaniment for Bass Viol',
    supplementary_title: '',
    price: 10,
    material_id: 7,
    category_id: 7,
    instrument_no: 2,
  },
  {
    id: 8,
    article_no: 'OM504',
    title:
      'Easy Baroque Pieces for Tenor Viol (8ve treble clef) with accompaniment for Bass Viol',
    supplementary_title: '(8ve treble clef)',
    price: 11,
    material_id: 8,
    category_id: 8,
    instrument_no: 2,
  },
  {
    id: 9,
    article_no: 'OM504A',
    title:
      'Easy Baroque Pieces for Tenor Viol (Alto clef) with accompaniment for Bass Viol',
    supplementary_title: '(alto clef)',
    price: 11,
    material_id: 9,
    category_id: 9,
    instrument_no: 2,
  },
  {
    id: 10,
    article_no: 'OM505',
    title: 'Easy Baroque Pieces for Bass Viol with accompaniment for Bass Viol',
    supplementary_title: '',
    price: 11,
    material_id: 10,
    category_id: 10,
    instrument_no: 2,
  },
  {
    id: 11,
    article_no: 'OM506',
    title:
      'Easy Renaissance Dances for Treble Viol with accompaniment for Bass Viol',
    supplementary_title: '',
    price: 11,
    material_id: 11,
    category_id: 11,
    instrument_no: 2,
  },
  {
    id: 12,
    article_no: 'OM507',
    title:
      'Easy Renaissance Dances for Tenor Viol with accompaniment for Bass Viol',
    supplementary_title: '',
    price: 12,
    material_id: 12,
    category_id: 12,
    instrument_no: 2,
  },
  {
    id: 13,
    article_no: 'OM508',
    title:
      'Easy Renaissance Dances for Bass Viol with accompaniment for Bass Viol',
    supplementary_title: '',
    price: 12,
    material_id: 13,
    category_id: 13,
    instrument_no: 2,
  },
  {
    id: 14,
    article_no: 'OM509',
    title:
      'Renaissance Songs from Germany, France, Spain, England & Italy for Treble Viol with accompaniment for Bass Viol',
    supplementary_title: '',
    price: 12,
    material_id: 14,
    category_id: 14,
    instrument_no: 2,
  },
  {
    id: 15,
    article_no: 'OM510',
    title:
      'Renaissance Songs from Germany, France, Spain, England & Italy for Tenor Viol with accompaniment for Bass Viol',
    supplementary_title: '',
    price: 13,
    material_id: 15,
    category_id: 15,
    instrument_no: 2,
  },
  {
    id: 16,
    article_no: 'OM511',
    title:
      'Renaissance Songs from Germany, France, Spain, England & Italy for Bass Viol with accompaniment for Bass Viol',
    supplementary_title: '',
    price: 13,
    material_id: 16,
    category_id: 16,
    instrument_no: 2,
  },
  {
    id: 17,
    article_no: 'OM512',
    title: 'French Duets for two Treble Viols, Volume 1',
    supplementary_title: '',
    price: 17,
    material_id: 17,
    category_id: 17,
    instrument_no: 2,
  },
  {
    id: 18,
    article_no: 'OM513',
    title: 'French Duets for two Tenor Viols, Volume 1',
    supplementary_title: '',
    price: 17,
    material_id: 18,
    category_id: 18,
    instrument_no: 2,
  },
  {
    id: 19,
    article_no: 'OM514',
    title: 'French Duets for two Bass Viols, Volume 1',
    supplementary_title: '',
    price: 17,
    material_id: 19,
    category_id: 19,
    instrument_no: 2,
  },
  {
    id: 20,
    article_no: 'OM522',
    title: 'French Duets for two Treble Viols, Volume 2',
    supplementary_title: '',
    price: 18,
    material_id: 20,
    category_id: 20,
    instrument_no: 2,
  },
  {
    id: 21,
    article_no: 'OM523',
    title: 'French Duets for two Tenor Viols, Volume 2',
    supplementary_title: '',
    price: 18,
    material_id: 21,
    category_id: 21,
    instrument_no: 2,
  },
  {
    id: 22,
    article_no: 'OM524',
    title: 'French Duets for two Bass Viols, Volume 2',
    supplementary_title: '',
    price: 18,
    material_id: 22,
    category_id: 22,
    instrument_no: 2,
  },
  {
    id: 23,
    article_no: 'OM525',
    title: 'London Duos for two Treble Viols',
    supplementary_title: '',
    price: 16,
    material_id: 23,
    category_id: 23,
    instrument_no: 2,
  },
  {
    id: 24,
    article_no: 'OM526',
    title: 'London Duos for two Tenor Viols',
    supplementary_title: '',
    price: 16,
    material_id: 24,
    category_id: 24,
    instrument_no: 2,
  },
  {
    id: 25,
    article_no: 'OM527',
    title: 'London Duos for two Bass Viols',
    supplementary_title: '',
    price: 16,
    material_id: 25,
    category_id: 25,
    instrument_no: 2,
  },
  {
    id: 26,
    article_no: 'OM516',
    title: 'Ten Easy Duets for Tenor & Bass Viols from Op. 66',
    supplementary_title: '',
    price: 15,
    material_id: 26,
    category_id: 26,
    instrument_no: 2,
  },
  {
    id: 27,
    article_no: 'OM515',
    title: 'Ten Easy Duets for Bass Viols from Op. 66',
    supplementary_title: '',
    price: 15,
    material_id: 27,
    category_id: 27,
    instrument_no: 2,
  },
  {
    id: 28,
    article_no: 'OM532',
    title: 'Eight Easy Divisions for Tenor Viol',
    supplementary_title: '',
    price: 15,
    material_id: 28,
    category_id: 28,
    instrument_no: 2,
  },
  {
    id: 29,
    article_no: 'OM533',
    title: 'Eight Easy Divisions for Bass Viol',
    supplementary_title: '',
    price: 15,
    material_id: 29,
    category_id: 29,
    instrument_no: 2,
  },
  {
    id: 30,
    article_no: 'OM528',
    title: 'Three Sonatas and a Suite for two Treble Viols',
    supplementary_title: '',
    price: 16,
    material_id: 30,
    category_id: 30,
    instrument_no: 2,
  },
  {
    id: 31,
    article_no: 'OM529',
    title: 'Three Sonatas and a Suite for two Tenor Viols',
    supplementary_title: '',
    price: 16,
    material_id: 31,
    category_id: 31,
    instrument_no: 2,
  },
  {
    id: 32,
    article_no: 'OM530',
    title: 'Three Sonatas and a Suite for two Bass Viols',
    supplementary_title: '',
    price: 16,
    material_id: 32,
    category_id: 32,
    instrument_no: 2,
  },
  {
    id: 33,
    article_no: 'OM517',
    title: 'Four Suites for Tenor & Bass Viols from Pieces a deux Basses, 1700',
    supplementary_title: '',
    price: 17,
    material_id: 33,
    category_id: 33,
    instrument_no: 2,
  },
  {
    id: 34,
    article_no: 'OM518',
    title: 'Four Suites for two Bass Viols from Pieces a deux Basses, 1700',
    supplementary_title: '',
    price: 17,
    material_id: 34,
    category_id: 34,
    instrument_no: 2,
  },
  {
    id: 35,
    article_no: 'OM531',
    title: 'Six Easy Baroque Sonatas for Bass Viol & Basso Continuo',
    supplementary_title: '',
    price: 20,
    material_id: 35,
    category_id: 35,
    instrument_no: 2,
  },
];
