// change to pascal case
//

type Edition = {
  id: number;
  articleNo: string;
  title: string;
  supplementaryTitle: string; // could be null
  price: number;
  materialId: number; // could be null
  categoryId: number;
  instrumentNo: number;
}[];

export const editions: Edition = [
  {
    id: 1,
    articleNo: 'OM501',
    title: 'Gambenschule für Kinder, 1. Teil (German only)',
    supplementaryTitle: '(German only)',
    price: 16,
    materialId: 1,
    categoryId: 1,
    instrumentNo: 1,
  },
  {
    id: 2,
    articleNo: 'OM502',
    title: 'Gambenschule für Kinder, 1. Teil (German only)',
    supplementaryTitle: '(German only)',
    price: 16,
    materialId: 2,
    categoryId: 2,
    instrumentNo: 1,
  },
  {
    id: 3,
    articleNo: 'OM521',
    title: 'Gambenschule für Kinder, 2. Teil (German only)',
    supplementaryTitle: '(German only)',
    price: 11,
    materialId: 3,
    categoryId: 3,
    instrumentNo: 1,
  },
  {
    id: 4,
    articleNo: 'OM520',
    title: 'Gambenschule für Kinder, 2. Teil (German only)',
    supplementaryTitle: '(German only)',
    price: 11,
    materialId: 4,
    categoryId: 4,
    instrumentNo: 1,
  },
  {
    id: 5,
    articleNo: 'OM519a',
    title: 'Weihnachtslieder für Diskant- & Altgambe',
    supplementaryTitle: '(German only)',
    price: 10,
    materialId: 5,
    categoryId: 5,
    instrumentNo: 2,
  },
  {
    id: 6,
    articleNo: 'OM519b',
    title: 'Weihnachtslieder für Alt- & Bassgambe',
    supplementaryTitle: '(German only)',
    price: 10,
    materialId: 6,
    categoryId: 6,
    instrumentNo: 2,
  },
  {
    id: 7,
    articleNo: 'OM503',
    title:
      'Easy Baroque Pieces for Treble Viol with accompaniment for Bass Viol',
    supplementaryTitle: '',
    price: 10,
    materialId: 7,
    categoryId: 7,
    instrumentNo: 2,
  },
  {
    id: 8,
    articleNo: 'OM504',
    title:
      'Easy Baroque Pieces for Tenor Viol (8ve treble clef) with accompaniment for Bass Viol',
    supplementaryTitle: '(8ve treble clef)',
    price: 11,
    materialId: 8,
    categoryId: 8,
    instrumentNo: 2,
  },
  {
    id: 9,
    articleNo: 'OM504A',
    title:
      'Easy Baroque Pieces for Tenor Viol (Alto clef) with accompaniment for Bass Viol',
    supplementaryTitle: '(alto clef)',
    price: 11,
    materialId: 9,
    categoryId: 9,
    instrumentNo: 2,
  },
  {
    id: 10,
    articleNo: 'OM505',
    title: 'Easy Baroque Pieces for Bass Viol with accompaniment for Bass Viol',
    supplementaryTitle: '',
    price: 11,
    materialId: 10,
    categoryId: 10,
    instrumentNo: 2,
  },
  {
    id: 11,
    articleNo: 'OM506',
    title:
      'Easy Renaissance Dances for Treble Viol with accompaniment for Bass Viol',
    supplementaryTitle: '',
    price: 11,
    materialId: 11,
    categoryId: 11,
    instrumentNo: 2,
  },
  {
    id: 12,
    articleNo: 'OM507',
    title:
      'Easy Renaissance Dances for Tenor Viol with accompaniment for Bass Viol',
    supplementaryTitle: '',
    price: 12,
    materialId: 12,
    categoryId: 12,
    instrumentNo: 2,
  },
  {
    id: 13,
    articleNo: 'OM508',
    title:
      'Easy Renaissance Dances for Bass Viol with accompaniment for Bass Viol',
    supplementaryTitle: '',
    price: 12,
    materialId: 13,
    categoryId: 13,
    instrumentNo: 2,
  },
  {
    id: 14,
    articleNo: 'OM509',
    title:
      'Renaissance Songs from Germany, France, Spain, England & Italy for Treble Viol with accompaniment for Bass Viol',
    supplementaryTitle: '',
    price: 12,
    materialId: 14,
    categoryId: 14,
    instrumentNo: 2,
  },
  {
    id: 15,
    articleNo: 'OM510',
    title:
      'Renaissance Songs from Germany, France, Spain, England & Italy for Tenor Viol with accompaniment for Bass Viol',
    supplementaryTitle: '',
    price: 13,
    materialId: 15,
    categoryId: 15,
    instrumentNo: 2,
  },
  {
    id: 16,
    articleNo: 'OM511',
    title:
      'Renaissance Songs from Germany, France, Spain, England & Italy for Bass Viol with accompaniment for Bass Viol',
    supplementaryTitle: '',
    price: 13,
    materialId: 16,
    categoryId: 16,
    instrumentNo: 2,
  },
  {
    id: 17,
    articleNo: 'OM512',
    title: 'French Duets for two Treble Viols, Volume 1',
    supplementaryTitle: '',
    price: 17,
    materialId: 17,
    categoryId: 17,
    instrumentNo: 2,
  },
  {
    id: 18,
    articleNo: 'OM513',
    title: 'French Duets for two Tenor Viols, Volume 1',
    supplementaryTitle: '',
    price: 17,
    materialId: 18,
    categoryId: 18,
    instrumentNo: 2,
  },
  {
    id: 19,
    articleNo: 'OM514',
    title: 'French Duets for two Bass Viols, Volume 1',
    supplementaryTitle: '',
    price: 17,
    materialId: 19,
    categoryId: 19,
    instrumentNo: 2,
  },
  {
    id: 20,
    articleNo: 'OM522',
    title: 'French Duets for two Treble Viols, Volume 2',
    supplementaryTitle: '',
    price: 18,
    materialId: 20,
    categoryId: 20,
    instrumentNo: 2,
  },
  {
    id: 21,
    articleNo: 'OM523',
    title: 'French Duets for two Tenor Viols, Volume 2',
    supplementaryTitle: '',
    price: 18,
    materialId: 21,
    categoryId: 21,
    instrumentNo: 2,
  },
  {
    id: 22,
    articleNo: 'OM524',
    title: 'French Duets for two Bass Viols, Volume 2',
    supplementaryTitle: '',
    price: 18,
    materialId: 22,
    categoryId: 22,
    instrumentNo: 2,
  },
  {
    id: 23,
    articleNo: 'OM525',
    title: 'London Duos for two Treble Viols',
    supplementaryTitle: '',
    price: 16,
    materialId: 23,
    categoryId: 23,
    instrumentNo: 2,
  },
  {
    id: 24,
    articleNo: 'OM526',
    title: 'London Duos for two Tenor Viols',
    supplementaryTitle: '',
    price: 16,
    materialId: 24,
    categoryId: 24,
    instrumentNo: 2,
  },
  {
    id: 25,
    articleNo: 'OM527',
    title: 'London Duos for two Bass Viols',
    supplementaryTitle: '',
    price: 16,
    materialId: 25,
    categoryId: 25,
    instrumentNo: 2,
  },
  {
    id: 26,
    articleNo: 'OM516',
    title: 'Ten Easy Duets for Tenor & Bass Viols from Op. 66',
    supplementaryTitle: '',
    price: 15,
    materialId: 26,
    categoryId: 26,
    instrumentNo: 2,
  },
  {
    id: 27,
    articleNo: 'OM515',
    title: 'Ten Easy Duets for Bass Viols from Op. 66',
    supplementaryTitle: '',
    price: 15,
    materialId: 27,
    categoryId: 27,
    instrumentNo: 2,
  },
  {
    id: 28,
    articleNo: 'OM532',
    title: 'Eight Easy Divisions for Tenor Viol',
    supplementaryTitle: '',
    price: 15,
    materialId: 28,
    categoryId: 28,
    instrumentNo: 2,
  },
  {
    id: 29,
    articleNo: 'OM533',
    title: 'Eight Easy Divisions for Bass Viol',
    supplementaryTitle: '',
    price: 15,
    materialId: 29,
    categoryId: 29,
    instrumentNo: 2,
  },
  {
    id: 30,
    articleNo: 'OM528',
    title: 'Three Sonatas and a Suite for two Treble Viols',
    supplementaryTitle: '',
    price: 16,
    materialId: 30,
    categoryId: 30,
    instrumentNo: 2,
  },
  {
    id: 31,
    articleNo: 'OM529',
    title: 'Three Sonatas and a Suite for two Tenor Viols',
    supplementaryTitle: '',
    price: 16,
    materialId: 31,
    categoryId: 31,
    instrumentNo: 2,
  },
  {
    id: 32,
    articleNo: 'OM530',
    title: 'Three Sonatas and a Suite for two Bass Viols',
    supplementaryTitle: '',
    price: 16,
    materialId: 32,
    categoryId: 32,
    instrumentNo: 2,
  },
  {
    id: 33,
    articleNo: 'OM517',
    title: 'Four Suites for Tenor & Bass Viols from Pieces a deux Basses, 1700',
    supplementaryTitle: '',
    price: 17,
    materialId: 33,
    categoryId: 33,
    instrumentNo: 2,
  },
  {
    id: 34,
    articleNo: 'OM518',
    title: 'Four Suites for two Bass Viols from Pieces a deux Basses, 1700',
    supplementaryTitle: '',
    price: 17,
    materialId: 34,
    categoryId: 34,
    instrumentNo: 2,
  },
  {
    id: 35,
    articleNo: 'OM531',
    title: 'Six Easy Baroque Sonatas for Bass Viol & Basso Continuo',
    supplementaryTitle: '',
    price: 20,
    materialId: 35,
    categoryId: 35,
    instrumentNo: 2,
  },
];
